/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n7.1.1-14-g7eaa8c110e-20250516"
#endif /* AVUTIL_FFVERSION_H */
